// src/components/encrypt/Encrypt.tsx
import { useState, useMemo, useCallback } from 'react';
import type { JSONContent } from '@tiptap/core';
import { useTranslation } from 'react-i18next';
import { useDataStore, isEncryptData } from '../../lib/dataStore';
import { 
  type SecretCheckboxState, 
  type HowData, 
  type IntroCheckboxState,
  defaultSecretCheckboxState, 
  defaultIntroCheckboxState 
} from '../../lib/types/editorTypes';
import type { Recipient } from '../../lib/types/recipient';
import { SecretEditor } from './SecretEditor';
import { WhoEditor } from './WhoEditor';
import { HowEditor } from './HowEditor';
import { IntroMessageEditor } from './IntroMessageEditor';
import { GenerateEditor } from './GenerateEditor';
import { StepIndicator } from '../ui/StepIndicator';
import styles from './Encrypt.module.css';

interface EncryptProps {
  onBack: () => void;
}

const defaultHowData: Partial<HowData> = {
  conditions: null,
  hasNoOpenConditions: false,
};

export function Encrypt({ onBack }: EncryptProps) {
  const storedData = useDataStore((state) => state.storedData);
  const { t } = useTranslation();
  
  // Type guard to ensure we have encrypt data
  const encryptData = isEncryptData(storedData) ? storedData : null;
  if (!encryptData) {
    throw new Error('Encrypt component requires encrypt mode data');
  }

  // Encrypt path state - initialized from context
  const [secretContent, setSecretContent] = useState(() => encryptData.what?.content ?? '');
  const [secretCheckboxState, setSecretCheckboxState] = useState<SecretCheckboxState>(() => ({
    ...defaultSecretCheckboxState,
    ...encryptData.what?.checkboxState,
  }));
  const [secretSubmitted, setSecretSubmitted] = useState(false);
  const [recipients, setRecipients] = useState<Recipient[]>(() => encryptData.who?.recipients ?? []);
  const [whoSubmitted, setWhoSubmitted] = useState(false);
  const [howData, setHowData] = useState<Partial<HowData>>(() => ({
    ...defaultHowData,
    ...encryptData.how,
  }));
  const [howSubmitted, setHowSubmitted] = useState(false);
  const [introMessage, setIntroMessage] = useState<JSONContent | null>(() => encryptData.intro?.message ?? null);
  const [introCheckboxState, setIntroCheckboxState] = useState<IntroCheckboxState>(() => ({
    ...defaultIntroCheckboxState,
    ...encryptData.intro?.checkboxState,
  }));
  const [introSubmitted, setIntroSubmitted] = useState(false);
  const [aesKey, setAesKey] = useState<Uint8Array | undefined>(() => encryptData.generate?.aesKey);
  const [shares] = useState<string[] | undefined>(() => encryptData.generate?.shares);
  const [generateSubmitted, setGenerateSubmitted] = useState(false);

  // Steps for encrypt mode
  const steps = useMemo(() => [
    { key: 'secret', label: t('steps.secret') },
    { key: 'who', label: t('steps.who') },
    { key: 'how', label: t('steps.how') },
    { key: 'intro', label: t('steps.intro') },
    { key: 'generate', label: t('steps.generate') },
  ], [t]);

  // Current step based on submitted state
  const currentStep = useMemo(() => {
    if (!secretSubmitted) return 0;
    if (!whoSubmitted) return 1;
    if (!howSubmitted) return 2;
    if (!introSubmitted) return 3;
    if (!generateSubmitted) return 4;
    return 4; // Stay on last step when completed
  }, [secretSubmitted, whoSubmitted, howSubmitted, introSubmitted, generateSubmitted]);

  const scrollToTop = useCallback(() => {
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        window.scrollTo({ top: 0, behavior: 'instant' });
        document.documentElement.scrollTop = 0;
        document.body.scrollTop = 0;
      });
    });
  }, []);

  // Secret handlers
  const handleSecretContinue = useCallback((secret: string, checkboxState: SecretCheckboxState) => {
    setSecretContent(secret);
    setSecretCheckboxState(checkboxState);
    setSecretSubmitted(true);
    scrollToTop();
  }, [scrollToTop]);

  const handleSecretBack = useCallback((secret: string, checkboxState: SecretCheckboxState) => {
    setSecretContent(secret);
    setSecretCheckboxState(checkboxState);
    onBack();
    scrollToTop();
  }, [onBack, scrollToTop]);

  // Who handlers
  const handleWhoContinue = useCallback((newRecipients: Recipient[]) => {
    setRecipients(newRecipients);
    setWhoSubmitted(true);
    scrollToTop();
  }, [scrollToTop]);

  const handleWhoBack = useCallback((newRecipients: Recipient[]) => {
    setRecipients(newRecipients);
    setSecretSubmitted(false);
    scrollToTop();
  }, [scrollToTop]);

  // How handlers
  const handleHowContinue = useCallback((data: HowData) => {
    setHowData(data);
    setHowSubmitted(true);
    scrollToTop();
  }, [scrollToTop]);

  const handleHowBack = useCallback((data: HowData) => {
    setHowData(data);
    setWhoSubmitted(false);
    scrollToTop();
  }, [scrollToTop]);

  // Intro handlers
  const handleIntroContinue = useCallback((message: JSONContent | null, checkboxState: IntroCheckboxState) => {
    setIntroMessage(message);
    setIntroCheckboxState(checkboxState);
    setIntroSubmitted(true);
    scrollToTop();
  }, [scrollToTop]);

  const handleIntroBack = useCallback((message: JSONContent | null, checkboxState: IntroCheckboxState) => {
    setIntroMessage(message);
    setIntroCheckboxState(checkboxState);
    setHowSubmitted(false);
    scrollToTop();
  }, [scrollToTop]);

  // Generate handlers
  const handleGenerateContinue = useCallback(() => {
    setGenerateSubmitted(true);
    scrollToTop();
  }, [scrollToTop]);

  const handleGenerateBack = useCallback(() => {
    // Synchronize recipients with store to get updated numbers
    if (encryptData.who?.recipients) {
      setRecipients(encryptData.who.recipients);
    }
    // Synchronize aesKey with store
    if (encryptData.generate?.aesKey instanceof Uint8Array) {
      setAesKey(encryptData.generate.aesKey);
    }
    setGenerateSubmitted(false);
    setIntroSubmitted(false);
    scrollToTop();
  }, [scrollToTop, encryptData]);

  return (
    <div className={styles.appContainer}>
      <StepIndicator steps={steps} currentStep={currentStep} />
      
      <div className={styles.stepContent}>
        {!secretSubmitted ? (
          <SecretEditor
            initialValue={secretContent}
            initialCheckboxState={secretCheckboxState}
            onContinue={handleSecretContinue}
            onBack={handleSecretBack}
          />
        ) : !whoSubmitted ? (
          <WhoEditor
            initialRecipients={recipients}
            onContinue={handleWhoContinue}
            onBack={handleWhoBack}
          />
        ) : !howSubmitted ? (
          <HowEditor
            recipientCount={recipients.length}
            initialData={howData}
            aesKey={aesKey}
            onContinue={handleHowContinue}
            onBack={handleHowBack}
          />
        ) : !introSubmitted ? (
          <IntroMessageEditor
            initialValue={introMessage}
            initialCheckboxState={introCheckboxState}
            threshold={howData.threshold!}
            conditions={howData.conditions ?? null}
            recipients={recipients}
            onContinue={handleIntroContinue}
            onBack={handleIntroBack}
          />
        ) : !generateSubmitted ? (
          <GenerateEditor
            secret={secretContent}
            recipients={recipients}
            threshold={howData.threshold!}
            aesKey={aesKey}
            shares={shares}
            onContinue={handleGenerateContinue}
            onBack={handleGenerateBack}
          />
        ) : (
          <main className={styles.stepContentMain}>
            <h1>For When I'm Gone</h1>
            <p>Secret has been saved. Next steps will appear here.</p>
          </main>
        )}
      </div>
    </div>
  );
}

export default Encrypt;

// src/components/encrypt/Encrypt.svelte
<script lang="ts">
  import type { JSONContent } from '@tiptap/core';
  import { tick } from 'svelte';
  import { getTranslations, type Language } from '../../lib/i18n';
  import { getStoredData, updateStoredData, type EncryptStoredData } from '../../lib/dataStore';
  import { 
    type SecretCheckboxState, 
    type HowData, 
    type IntroCheckboxState,
    defaultSecretCheckboxState, 
    defaultIntroCheckboxState 
  } from '../../lib/types/editorTypes';
  import type { Recipient } from '../../lib/types/recipient';
  import SecretEditor from './SecretEditor.svelte';
  import WhoEditor from './WhoEditor.svelte';
  import HowEditor from './HowEditor.svelte';
  import IntroMessageEditor from './IntroMessageEditor.svelte';
  import GenerateEditor from './GenerateEditor.svelte';
  import StepIndicator from '../ui/StepIndicator.svelte';

  interface Props {
    lang: Language;
    onBack: () => void;
    onLanguageChange: (lang: Language) => void;
  }

  let { lang, onBack, onLanguageChange }: Props = $props();

  const defaultHowData: Partial<HowData> = {
    conditions: null,
    hasNoOpenConditions: false,
  };

  // Load initial data from stored JSON
  let initialStoredData = getStoredData() as EncryptStoredData;

  // ===== Encrypt path state =====
  let secretContent: string = $state(initialStoredData.what?.content ?? '');
  let secretCheckboxState: SecretCheckboxState = $state({
    ...defaultSecretCheckboxState,
    ...initialStoredData.what?.checkboxState,
  });
  let secretSubmitted: boolean = $state(false);
  let recipients: Recipient[] = $state(initialStoredData.who?.recipients ?? []);
  let whoSubmitted: boolean = $state(false);
  let howData: Partial<HowData> = $state({
    ...defaultHowData,
    ...initialStoredData.how,
  });
  let howSubmitted: boolean = $state(false);
  let introMessage: JSONContent | null = $state(initialStoredData.intro?.message ?? null);
  let introCheckboxState: IntroCheckboxState = $state({
    ...defaultIntroCheckboxState,
    ...initialStoredData.intro?.checkboxState,
  });
  let introSubmitted: boolean = $state(false);
  let aesKey: Uint8Array | undefined = $state(initialStoredData.generate?.aesKey);
  let shares: string[] | undefined = $state(initialStoredData.generate?.shares);
  let generateSubmitted: boolean = $state(false);

  let t = $derived(getTranslations(lang));

  // Steps for encrypt mode
  let steps = $derived([
    { key: 'secret', label: t.steps.secret },
    { key: 'who', label: t.steps.who },
    { key: 'how', label: t.steps.how },
    { key: 'intro', label: t.steps.intro },
    { key: 'generate', label: t.steps.generate },
  ]);

  // Current step based on submitted state
  let currentStep = $derived.by(() => {
    if (!secretSubmitted) return 0;
    if (!whoSubmitted) return 1;
    if (!howSubmitted) return 2;
    if (!introSubmitted) return 3;
    if (!generateSubmitted) return 4;
    return 4; // Stay on last step when completed
  });

  async function scrollToTop(): Promise<void> {
    await tick();
    requestAnimationFrame(() => {
      requestAnimationFrame(() => {
        window.scrollTo({ top: 0, behavior: 'instant' });
        document.documentElement.scrollTop = 0;
        document.body.scrollTop = 0;
      });
    });
  }

  // ===== What (Secret) handlers =====
  async function handleSecretContinue(secret: string, checkboxState: SecretCheckboxState): Promise<void> {
    secretContent = secret;
    secretCheckboxState = checkboxState;
    secretSubmitted = true;
    await scrollToTop();
  }

  async function handleSecretBack(secret: string, checkboxState: SecretCheckboxState): Promise<void> {
    secretContent = secret;
    secretCheckboxState = checkboxState;
    onBack();
    await scrollToTop();
  }

  // ===== Who handlers =====
  async function handleWhoContinue(newRecipients: Recipient[]): Promise<void> {
    recipients = newRecipients;
    whoSubmitted = true;
    await scrollToTop();
  }

  async function handleWhoBack(newRecipients: Recipient[]): Promise<void> {
    recipients = newRecipients;
    secretSubmitted = false;
    await scrollToTop();
  }

  // ===== How handlers =====
  async function handleHowContinue(data: HowData): Promise<void> {
    howData = data;
    howSubmitted = true;
    await scrollToTop();
  }

  async function handleHowBack(data: HowData): Promise<void> {
    howData = data;
    whoSubmitted = false;
    await scrollToTop();
  }

  // ===== Intro handlers =====
  async function handleIntroContinue(message: JSONContent | null, checkboxState: IntroCheckboxState): Promise<void> {
    introMessage = message;
    introCheckboxState = checkboxState;
    introSubmitted = true;
    await scrollToTop();
  }

  async function handleIntroBack(message: JSONContent | null, checkboxState: IntroCheckboxState): Promise<void> {
    introMessage = message;
    introCheckboxState = checkboxState;
    howSubmitted = false;
    await scrollToTop();
  }

  // ===== Generate handlers =====
  async function handleGenerateContinue(): Promise<void> {
    generateSubmitted = true;
    await scrollToTop();
  }

  async function handleGenerateBack(): Promise<void> {
    const storedData = getStoredData() as EncryptStoredData;
    // Synchronize recipients with store to get updated numbers
    if (storedData.who?.recipients) {
      recipients = storedData.who.recipients;
    }
    generateSubmitted = false;
    introSubmitted = false;
    await scrollToTop();
  }

  // Synchronize aesKey with store when on HowEditor screen
  $effect(() => {
    if (!howSubmitted && secretSubmitted && whoSubmitted) {
      const storedData = getStoredData() as EncryptStoredData;
      if (storedData.generate?.aesKey instanceof Uint8Array) {
        aesKey = storedData.generate.aesKey;
      }
    }
  });
</script>

<div class="app-container">
  <StepIndicator {steps} {currentStep} />
  
  <div class="step-content">
    {#if !secretSubmitted}
      <SecretEditor
        {lang}
        initialValue={secretContent}
        initialCheckboxState={secretCheckboxState}
        onContinue={handleSecretContinue}
        onBack={handleSecretBack}
      />
    {:else if !whoSubmitted}
      <WhoEditor
        {lang}
        initialRecipients={recipients}
        onContinue={handleWhoContinue}
        onBack={handleWhoBack}
      />
    {:else if !howSubmitted}
      <HowEditor
        {lang}
        recipientCount={recipients.length}
        initialData={howData}
        {aesKey}
        onContinue={handleHowContinue}
        onBack={handleHowBack}
      />
    {:else if !introSubmitted}
      <IntroMessageEditor
        {lang}
        initialValue={introMessage}
        initialCheckboxState={introCheckboxState}
        threshold={howData.threshold!}
        conditions={howData.conditions ?? null}
        {recipients}
        onContinue={handleIntroContinue}
        onBack={handleIntroBack}
      />
    {:else if !generateSubmitted}
      <GenerateEditor
        {lang}
        secret={secretContent}
        recipients={recipients}
        threshold={howData.threshold!}
        {aesKey}
        {shares}
        onContinue={handleGenerateContinue}
        onBack={handleGenerateBack}
      />
    {:else}
      <main>
        <h1>For When I'm Gone</h1>
        <p>Secret has been saved. Next steps will appear here.</p>
      </main>
    {/if}
  </div>
</div>

<style>
  .app-container {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
  }

  .step-content {
    flex: 1;
    display: flex;
    flex-direction: column;
  }

  main {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    flex: 1;
    gap: 1.5rem;
    padding: 2rem;
  }

  h1 {
    font-size: 2.5rem;
    color: #ffffff;
  }

  p {
    color: #a0aec0;
    max-width: 500px;
  }
</style>
