// src/components/encrypt/what/SecretEditor.tsx
import { useCallback, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { EncryptStoreActions, useEncryptDataStore } from '../../../lib/dataStore';
import { defaultSecretCheckboxState, SecretCheckboxState } from '../../../lib/types/editorTypes';
import { EditorLayout } from '../../ui/EditorLayout';
import { CheckboxItem } from '../../ui/CheckboxItem';
import { ActionButtons } from '../../ui/ActionButtons';
import { EssentialSection } from '../../ui/EssentialSection';
import { HelpSection } from '../../ui/HelpSection';
import formControls from '../../../styles/form-controls.module.css';
import styles from './SecretEditor.module.css';
import { TFunction } from 'i18next';

interface SecretEditorProps {
  onContinue: () => void;
  onBack: () => void;
}

export function SecretEditor({ onContinue, onBack }: SecretEditorProps) {
  const { t } = useTranslation();
  const getData: EncryptStoreActions['getData'] = useEncryptDataStore(state => state.getData);
  const setData: EncryptStoreActions['setData'] = useEncryptDataStore(state => state.setData);
  const initialSecret = getData().what?.content ?? '';
  const [content, setContent] = useState(initialSecret);
  const checkboxState = useEncryptDataStore((state) => state.what?.checkboxState ?? defaultSecretCheckboxState);

  const handleContentChange = useCallback((content: string) => {
    setData((current) => ({
      what: { ...current.what, content: content }
    }));
    setContent(content);
  }, []);

  const handleEditorChange = useCallback((event: React.ChangeEvent<HTMLTextAreaElement>) => {
    handleContentChange(event.target.value);
  }, [handleContentChange]);
  
  const generateExample = useCallback(() => {
    const example = t('secretEditor.sidePanel.exampleContent');
    handleContentChange(example);
  }, [t, handleContentChange]);

  const isEmpty = content.trim() === '';
  
  // Calculer la variante pour le bouton
  const essentials = [
    checkboxState.emails,
    checkboxState.phoneCodes,
    checkboxState.cloudAccounts
  ];
  const optional = [
    checkboxState.computerLogins,
    checkboxState.otherPasswords,
    checkboxState.domainManager,
    checkboxState.passwordManager,
    checkboxState.backups,
    checkboxState.crypto
  ];
  const { variant, title } = getVariantAndTitle(content, essentials, optional, t);

  return (
    <EditorLayout title={t('secretEditor.title')}>
      <textarea
        value={content}
        onChange={handleEditorChange}
        autoComplete="off"
        className={formControls.formTextarea}
        placeholder={t('secretEditor.placeholder')}
      />

      
      <HelpContent title={title}/>

      <ActionButtons
        backLabel={t('common.back')}
        continueLabel={t('common.continue')}
        buttonState={isEmpty ? "none" : "complete"}
        disabled={false}
        onBack={onBack}
        onContinue={onContinue}
        showAlternative={isEmpty}
        alternativeLabel={t('secretEditor.sidePanel.generateExample')}
        onAlternative={generateExample}
        variant={variant}
      />
    </EditorLayout>
  );
}


function getVariantAndTitle(content: string, essentials: boolean[], optional: boolean[], t: TFunction): { variant: 'error' | 'warning' | 'info' | 'success', title: string } {
  const isEmpty = content.trim() === '';
  const essentialCount = essentials.filter(Boolean).length;
  const essentialTotal = essentials.length;
  const allCheckedCount = essentialCount + optional.filter(Boolean).length;
  const allTotal = essentialTotal + optional.length;
  const allChecked = allCheckedCount === allTotal;
  const allEssentialChecked = essentialCount === essentialTotal;

  if (allChecked) {
    return {
      variant: 'success',
      title: t('secretEditor.sidePanel.successTitle', { count: allCheckedCount, total: allTotal })
    };
  }
  if (allEssentialChecked) {
    return {
      variant: 'info',
      title: t('secretEditor.sidePanel.infoTitle', { count: allCheckedCount, total: allTotal })
    };
  }
  if (isEmpty) {
    return {
      variant: 'error',
      title: t('secretEditor.sidePanel.errorTitle')
    };
  }
  return {
    variant: 'warning',
    title: t('secretEditor.sidePanel.warningTitle', { count: essentialCount, total: essentialTotal })
  };
}

function HelpContent({ title }: { title: string }) {
  const { t } = useTranslation();
  const checkboxState = useEncryptDataStore((state) => state.what?.checkboxState ?? defaultSecretCheckboxState);
  const setData: EncryptStoreActions['setData'] = useEncryptDataStore((state) => state.setData);
  
  const handleCheckboxChange = (key: string, checked: boolean) => {
    setData((current) => ({
      what: { ...current.what, checkboxState: { ...current.what?.checkboxState ?? defaultSecretCheckboxState, [key]: checked } }
    }));
  };

  return (
    <HelpSection title={title}>
      <EssentialSection note={t('secretEditor.sidePanel.essentialNote')}>
        <CheckBox name="emails" state={checkboxState.emails} essential={true} handleCheckboxChange={handleCheckboxChange} />
        <CheckBox name="phoneCodes" state={checkboxState.phoneCodes} essential={true} handleCheckboxChange={handleCheckboxChange} />
        <CheckBox name="cloudAccounts" state={checkboxState.cloudAccounts} essential={true} handleCheckboxChange={handleCheckboxChange} />
      </EssentialSection>

      <div className={styles.regularSection}>
        <CheckBox name="computerLogins" state={checkboxState.computerLogins} essential={false} handleCheckboxChange={handleCheckboxChange} />
        <CheckBox name="otherPasswords" state={checkboxState.otherPasswords} essential={false} handleCheckboxChange={handleCheckboxChange} />
      </div>

      <div className={formControls.optionalSection}>
        <h3>{t('secretEditor.sidePanel.sectionOptional')}</h3>
        <CheckBox name="domainManager" state={checkboxState.domainManager} essential={false} handleCheckboxChange={handleCheckboxChange} />
        <CheckBox name="passwordManager" state={checkboxState.passwordManager} essential={false} handleCheckboxChange={handleCheckboxChange} />
        <CheckBox name="backups" state={checkboxState.backups} essential={false} handleCheckboxChange={handleCheckboxChange} />
        <CheckBox name="crypto" state={checkboxState.crypto} essential={false} handleCheckboxChange={handleCheckboxChange} />
      </div>
    </HelpSection>
  );
}

function CheckBox({ name, state, essential, handleCheckboxChange }: { name: keyof SecretCheckboxState, state: SecretCheckboxState, essential: boolean, handleCheckboxChange: (name: keyof SecretCheckboxState, checked: boolean) => void }) {
  const { t } = useTranslation();
  return (
    <CheckboxItem
      label={t(`secretEditor.sidePanel.checkboxes.${name}`)}
      checked={state[name]}
      essential={essential}
      onChange={(checked) => handleCheckboxChange(name, checked)}
    />
  );
}

// src/components/SecretEditor.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { getTranslations, type Language } from '../lib/i18n';
  import { computeButtonState, getButtonText } from '../lib/buttonState';
  import { updateStoredDataDebounced } from '../lib/dataStore';
  import { type SecretCheckboxState, defaultSecretCheckboxState } from '../lib/types/editorTypes';
  import EditorLayout from './ui/EditorLayout.svelte';
  import CheckboxItem from './ui/CheckboxItem.svelte';
  import ActionButtons from './ui/ActionButtons.svelte';
  import EssentialSection from './ui/EssentialSection.svelte';
  import GenerateExampleButton from './ui/GenerateExampleButton.svelte';
  import '../styles/form-controls.css';

  export type { SecretCheckboxState };
  export { defaultSecretCheckboxState };

  interface Props {
    lang: Language;
    initialValue?: string;
    initialCheckboxState?: SecretCheckboxState;
    onContinue: (secret: string, checkboxState: SecretCheckboxState) => void;
    onBack: (secret: string, checkboxState: SecretCheckboxState) => void;
  }

  let { lang, initialValue, initialCheckboxState, onContinue, onBack }: Props = $props();

  let secretText: string = $state(untrack(() => initialValue ?? ''));
  let sidePanelOpen: boolean = $state(true);

  // Checkbox states
  let checkEmails: boolean = $state(untrack(() => initialCheckboxState?.emails ?? false));
  let checkPhoneCodes: boolean = $state(untrack(() => initialCheckboxState?.phoneCodes ?? false));
  let checkCloudAccounts: boolean = $state(untrack(() => initialCheckboxState?.cloudAccounts ?? false));
  let checkComputerLogins: boolean = $state(untrack(() => initialCheckboxState?.computerLogins ?? false));
  let checkOtherPasswords: boolean = $state(untrack(() => initialCheckboxState?.otherPasswords ?? false));
  let checkDomainManager: boolean = $state(untrack(() => initialCheckboxState?.domainManager ?? false));
  let checkPasswordManager: boolean = $state(untrack(() => initialCheckboxState?.passwordManager ?? false));
  let checkBackups: boolean = $state(untrack(() => initialCheckboxState?.backups ?? false));
  let checkCrypto: boolean = $state(untrack(() => initialCheckboxState?.crypto ?? false));

  let t = $derived(getTranslations(lang));

  let hasContent = $derived(secretText.trim().length > 0);
  let essentialsChecked = $derived(checkEmails && checkPhoneCodes && checkCloudAccounts);
  let anyChecked = $derived(
    checkEmails || checkPhoneCodes || checkCloudAccounts ||
    checkComputerLogins || checkOtherPasswords ||
    checkDomainManager || checkPasswordManager || checkBackups || checkCrypto
  );

  let buttonState = $derived(computeButtonState(hasContent, anyChecked, essentialsChecked));
  let buttonText = $derived(hasContent ? getButtonText(buttonState, t.secretEditor.buttons) : t.secretEditor.buttons.continue);

  function getCurrentCheckboxState(): SecretCheckboxState {
    return {
      emails: checkEmails,
      phoneCodes: checkPhoneCodes,
      cloudAccounts: checkCloudAccounts,
      computerLogins: checkComputerLogins,
      otherPasswords: checkOtherPasswords,
      domainManager: checkDomainManager,
      passwordManager: checkPasswordManager,
      backups: checkBackups,
      crypto: checkCrypto,
    };
  }

  function handleContinue(): void {
    if (hasContent) onContinue(secretText, getCurrentCheckboxState());
  }

  function handleBack(): void {
    onBack(secretText, getCurrentCheckboxState());
  }

  function generateExample(): void {
    const example = t.secretEditor.sidePanel.exampleContent;
    secretText = secretText.trim() ? secretText + '\n\n\n' + example : example;
  }

  // Auto-save
  $effect(() => {
    updateStoredDataDebounced({
      what: { content: secretText, checkboxState: getCurrentCheckboxState() },
    });
  });
</script>

<EditorLayout
  title={t.secretEditor.title}
  {sidePanelOpen}
  collapseLabel={t.secretEditor.sidePanel.collapse}
  expandLabel={t.secretEditor.sidePanel.expand}
  onToggleSidePanel={() => sidePanelOpen = !sidePanelOpen}
>
  <textarea
    autocomplete="off"
    class="form-textarea"
    bind:value={secretText}
    placeholder={t.secretEditor.placeholder}
  ></textarea>

  <ActionButtons
    backLabel={t.common.back}
    continueLabel={buttonText}
    {buttonState}
    disabled={!hasContent}
    onBack={handleBack}
    onContinue={handleContinue}
  />

  {#snippet sidePanelContent()}
    <h2>{t.secretEditor.sidePanel.title}</h2>

    <EssentialSection note={t.secretEditor.sidePanel.essentialNote}>
      <CheckboxItem
        bind:checked={checkEmails}
        label={t.secretEditor.sidePanel.checkboxes.emails}
        essential
      />
      <CheckboxItem
        bind:checked={checkPhoneCodes}
        label={t.secretEditor.sidePanel.checkboxes.phoneCodes}
        essential
      />
      <CheckboxItem
        bind:checked={checkCloudAccounts}
        label={t.secretEditor.sidePanel.checkboxes.cloudAccounts}
        essential
      />
    </EssentialSection>

    <div class="regular-section">
      <CheckboxItem
        bind:checked={checkComputerLogins}
        label={t.secretEditor.sidePanel.checkboxes.computerLogins}
      />
      <CheckboxItem
        bind:checked={checkOtherPasswords}
        label={t.secretEditor.sidePanel.checkboxes.otherPasswords}
      />
    </div>

    <div class="optional-section">
      <h3>{t.secretEditor.sidePanel.sectionOptional}</h3>
      <CheckboxItem
        bind:checked={checkDomainManager}
        label={t.secretEditor.sidePanel.checkboxes.domainManager}
      />
      <CheckboxItem
        bind:checked={checkPasswordManager}
        label={t.secretEditor.sidePanel.checkboxes.passwordManager}
      />
      <CheckboxItem
        bind:checked={checkBackups}
        label={t.secretEditor.sidePanel.checkboxes.backups}
      />
      <CheckboxItem
        bind:checked={checkCrypto}
        label={t.secretEditor.sidePanel.checkboxes.crypto}
      />
    </div>

    <div class="section-divider"></div>

    <GenerateExampleButton
      label={t.secretEditor.sidePanel.generateExample}
      onclick={generateExample}
    />
  {/snippet}
</EditorLayout>
