// src/components/ui/ContactRow.tsx
import type { ContactInfo } from '../../lib/types/recipient';
import { Icon } from './Icons';

interface ContactTypeOption {
  value: string;
  label: string;
}

interface ContactRowProps {
  contact: ContactInfo;
  contactTypeOptions: ContactTypeOption[];
  placeholders: { value: string };
  removeTitle: string;
  onTypeChange: (type: string) => void;
  onValueChange: (value: string) => void;
  onRemove: () => void;
}

export function ContactRow({
  contact,
  contactTypeOptions,
  placeholders,
  removeTitle,
  onTypeChange,
  onValueChange,
  onRemove,
}: ContactRowProps) {
  return (
    <div className="contact-row">
      <select
        className="form-select contact-type"
        value={contact.type}
        onChange={(e) => onTypeChange(e.target.value)}
      >
        {contactTypeOptions.map((option) => (
          <option key={option.value} value={option.value}>
            {option.label}
          </option>
        ))}
      </select>
      <input
        className="form-input contact-value"
        type="text"
        value={contact.value}
        onChange={(e) => onValueChange(e.target.value)}
        placeholder={placeholders.value}
      />
      <button
        className="remove-button"
        onClick={onRemove}
        title={removeTitle}
      >
        <Icon name="minus" size={14} />
      </button>
    </div>
  );
}

export default ContactRow;

// src/components/ui/ContactRow.svelte
<script lang="ts">
  import type { ContactInfo } from '../../lib/types/recipient';
  import Icon from './Icons.svelte';

  interface ContactTypeOption {
    value: string;
    label: string;
  }

  interface Props {
    contact: ContactInfo;
    contactTypeOptions: ContactTypeOption[];
    placeholders: { value: string };
    removeTitle: string;
    onTypeChange: (type: string) => void;
    onValueChange: (value: string) => void;
    onRemove: () => void;
  }

  let {
    contact,
    contactTypeOptions,
    placeholders,
    removeTitle,
    onTypeChange,
    onValueChange,
    onRemove,
  }: Props = $props();
</script>

<div class="contact-row">
  <select
    class="form-select contact-type"
    value={contact.type}
    onchange={(e) => onTypeChange(e.currentTarget.value)}
  >
    {#each contactTypeOptions as option}
      <option value={option.value}>{option.label}</option>
    {/each}
  </select>
  <input
    class="form-input contact-value"
    type="text"
    value={contact.value}
    oninput={(e) => onValueChange(e.currentTarget.value)}
    placeholder={placeholders.value}
  />
  <button
    class="remove-button"
    onclick={onRemove}
    title={removeTitle}
  >
    <Icon name="minus" size={14} />
  </button>
</div>
