// src/components/ui/EditorLayout.tsx
import { ReactNode } from 'react';
import { SidePanel } from './SidePanel';
import './EditorLayout.css';

interface EditorLayoutProps {
  title?: string;
  subtitle?: string;
  sidePanelOpen: boolean;
  collapseLabel: string;
  expandLabel: string;
  wideSidePanel?: boolean;
  onToggleSidePanel: () => void;
  children: ReactNode;
  sidePanelContent: ReactNode;
  toolbar?: ReactNode;
  editorId?: string;
}

export function EditorLayout({ 
  title,
  subtitle,
  sidePanelOpen, 
  collapseLabel, 
  expandLabel, 
  wideSidePanel = false,
  onToggleSidePanel, 
  children,
  sidePanelContent,
  toolbar,
  editorId
}: EditorLayoutProps) {
  return (
    <div className="editor-container">
      <main className={`main-content ${!sidePanelOpen ? 'panel-closed' : ''}`}>
        <div className="editor-wrapper">
          {title && <h1 className="editor-title">{title}</h1>}
          {subtitle && <p className="editor-subtitle">{subtitle}</p>}
          
          {toolbar}

          {children}
        </div>
      </main>

      <SidePanel
        open={sidePanelOpen}
        collapseLabel={collapseLabel}
        expandLabel={expandLabel}
        wide={wideSidePanel}
        onToggle={onToggleSidePanel}
        editorId={editorId}
      >
        {sidePanelContent}
      </SidePanel>
    </div>
  );
}

export default EditorLayout;

// src/components/ui/EditorLayout.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import SidePanel from './SidePanel.svelte';

  interface Props {
    title?: string;
    subtitle?: string;
    sidePanelOpen: boolean;
    collapseLabel: string;
    expandLabel: string;
    wideSidePanel?: boolean;
    onToggleSidePanel: () => void;
    children: Snippet;
    sidePanelContent: Snippet;
    toolbar?: Snippet;
    editorId?: string;
  }

  let { 
    title,
    subtitle,
    sidePanelOpen, 
    collapseLabel, 
    expandLabel, 
    wideSidePanel = false,
    onToggleSidePanel, 
    children,
    sidePanelContent,
    toolbar,
    editorId
  }: Props = $props();
</script>

<div class="editor-container">
  <main class="main-content" class:panel-closed={!sidePanelOpen}>
    <div class="editor-wrapper">
      {#if title}
        <h1 class="editor-title">{title}</h1>
      {/if}
      {#if subtitle}
        <p class="editor-subtitle">{subtitle}</p>
      {/if}
      
      {#if toolbar}
        {@render toolbar()}
      {/if}

      {@render children()}
    </div>
  </main>

  <SidePanel
    open={sidePanelOpen}
    {collapseLabel}
    {expandLabel}
    wide={wideSidePanel}
    onToggle={onToggleSidePanel}
    {editorId}
  >
    {@render sidePanelContent()}
  </SidePanel>
</div>

<style>
  .editor-container {
    display: flex;
    flex: 1;
    min-height: 0;
  }

  .main-content {
    flex: 1;
    display: flex;
    flex-direction: column;
    padding: 2rem;
    transition: margin-right 0.3s ease;
  }

  .main-content.panel-closed {
    margin-right: 0;
  }

  .editor-wrapper {
    flex: 1;
    display: flex;
    flex-direction: column;
    max-width: 900px;
    width: 100%;
    margin: 0 auto;
  }

  .editor-title {
    font-family: 'Georgia', 'Times New Roman', serif;
    font-size: 2rem;
    font-weight: 600;
    color: #ffffff;
    margin-bottom: 0.5rem;
    text-align: center;
  }

  .editor-subtitle {
    color: #a0aec0;
    text-align: center;
    margin-bottom: 1.5rem;
    font-size: 1rem;
  }

  /* Responsive */
  @media (max-width: 900px) {
    .main-content {
      margin-right: 50px;
    }

    .main-content.panel-closed {
      margin-right: 50px;
    }
  }

  @media (max-width: 600px) {
    .editor-container {
      flex-direction: column;
    }

    .main-content {
      margin-right: 0;
      padding: 1rem;
      padding-bottom: 70px;
    }

    .main-content.panel-closed {
      margin-right: 0;
    }

    .editor-title {
      font-size: 1.5rem;
    }
  }
</style>
