// src/components/encrypt/recipients/RecipientCard.tsx
import { useEffect, useRef, type DragEvent } from 'react';
import type { Recipient } from '../../../lib/types/recipient';
import { ContactRow } from './ContactRow';
import { Icon } from '../../ui/Icons';
import formControls from '../../../styles/form-controls.module.css';
import styles from './RecipientCard.module.css';
import { useRecipientActions } from './useRecipients';

interface ContactTypeOption {
  value: string;
  label: string;
}

interface Translations {
  newRecipient: string;
  removeRecipient: string;
  addContact: string;
  removeContact: string;
  fields: {
    name: string;
    contacts: string;
    notListedPublicly: string;
    privateInfo: string;
    numberedInfo: string;
  };
  placeholders: {
    name: string;
    contactValue: string;
  };
}

interface RecipientCardProps {
  recipient: Recipient;
  expanded: boolean;
  dragging: boolean;
  contactTypeOptions: ContactTypeOption[];
  translations: Translations;
  onDragStart: (e: DragEvent) => void;
  onDragEnd: () => void;
  autoFocus?: boolean;
  toggleDisabled?: boolean;
  onExpand: () => void;
  onCollapse: () => void;
}

function DragHandle() {
  return (
    <div
      className={styles.dragHandle}
      role="presentation"
      onClick={(e) => e.stopPropagation()}
      onKeyDown={(e) => e.stopPropagation()}
    >
      <Icon name="grip-vertical" size={18} />
    </div>
  );
}

interface RecipientNameInputProps {
  recipient: Recipient;
  nameInputRef: React.RefObject<HTMLInputElement>;
  placeholder: string;
  privateInfo: string;
  numberedInfo: string;
}

function RecipientNameInput({
  recipient,
  nameInputRef,
  placeholder,
  privateInfo,
  numberedInfo,
}: RecipientNameInputProps) {
  const { updateRecipientName } = useRecipientActions();
  return (
    <div className={styles.nameInputWrapper}>
      <input
        ref={nameInputRef}
        id={`name-${recipient.id}`}
        type="text"
        className={`${formControls.formInput} ${styles.recipientNameInput}`}
        value={recipient.name}
        onChange={(e) => updateRecipientName(recipient.id, e.target.value)}
        placeholder={placeholder}
      />
      {recipient.isPrivate ? (
        <div className={styles.privateInfoMessage}>
          {privateInfo}
        </div>
      ) : recipient.number ? (
        <div className={styles.privateInfoMessage}>
          {numberedInfo}
        </div>
      ) : null}
    </div>
  );
}

interface RecipientNameDisplayProps {
  recipient: Recipient;
  newRecipient: string;
}

function RecipientNameDisplay({ recipient, newRecipient }: RecipientNameDisplayProps) {
  return (
    <span className={`${styles.recipientName} ${recipient.isPrivate ? styles.private : ''}`}>
      {recipient.name || newRecipient}
      {recipient.number !== undefined && (
        <span className={styles.recipientNumber}> (#{recipient.number})</span>
      )}
    </span>
  );
}

interface RecipientSummaryProps {
  recipient: Recipient;
  expanded: boolean;
  nameInputRef: React.RefObject<HTMLInputElement>;
  translations: Translations;
}

function RecipientSummary({
  recipient,
  expanded,
  nameInputRef,
  translations: t,
}: RecipientSummaryProps) {
  return (
    <div className={styles.recipientSummary}>
      {expanded ? (
        <RecipientNameInput
          recipient={recipient}
          nameInputRef={nameInputRef}
          placeholder={t.placeholders.name}
          privateInfo={t.fields.privateInfo}
          numberedInfo={t.fields.numberedInfo}
        />
      ) : (
        <RecipientNameDisplay
          recipient={recipient}
          newRecipient={t.newRecipient}
        />
      )}
    </div>
  );
}

interface RecipientActionsProps {
  recipient: Recipient;
  expanded: boolean;
  translations: Translations;
}

function RecipientActions({
  recipient,
  expanded,
  translations: t,
}: RecipientActionsProps) {
  
  const { removeRecipient, updateRecipientVisibility } = useRecipientActions();

  return (
    <div className={styles.recipientActions}>
      {expanded && (
        <button
          className={styles.privateToggleButton}
          onClick={() => updateRecipientVisibility(recipient.id, !recipient.isPrivate)}
          title={t.fields.notListedPublicly}
        >
          <Icon name={recipient.isPrivate ? 'eye-off' : 'eye'} size={18} />
        </button>
      )}
      {expanded && !recipient.number && (
        <button
          className={`${styles.removeButton} ${styles.large}`}
          onClick={() => { removeRecipient(recipient.id) }}
          title={t.removeRecipient}
        >
          <Icon name="minus" size={16} />
        </button>
      )}
      <span className={`${styles.expandIcon} ${expanded ? styles.rotated : ''}`}>
        <Icon name="chevron-right" size={20} />
      </span>
    </div>
  );
}

interface RecipientDetailsProps {
  recipient: Recipient;
  contactTypeOptions: ContactTypeOption[];
  translations: Translations;
}

function RecipientDetails({
  recipient,
  contactTypeOptions,
  translations: t,
}: RecipientDetailsProps) {
  const { addRecipientContact, removeRecipientContact, updateRecipientContact } = useRecipientActions();
  return (
    <div className={styles.recipientDetails}>
      <div className={styles.contactsSection}>
        {recipient.contacts.map((contact) => (
          <ContactRow
            key={contact.id}
            contact={contact}
            contactTypeOptions={contactTypeOptions}
            placeholders={{ value: t.placeholders.contactValue }}
            removeTitle={t.removeContact}
            onTypeChange={(type) => updateRecipientContact(recipient.id, contact.id, 'type', type)}
            onValueChange={(value) => updateRecipientContact(recipient.id, contact.id, 'value', value)}
            onRemove={() => removeRecipientContact(recipient.id, contact.id)}
          />
        ))}

        <button className={styles.addButton} onClick={() => addRecipientContact(recipient.id)}>
          <Icon name="plus" size={16} />
          {t.addContact}
        </button>
      </div>
    </div>
  );
}

export function RecipientCard({
  recipient,
  expanded,
  dragging,
  contactTypeOptions,
  translations: t,
  onDragStart,
  onDragEnd,
  autoFocus = false,
  toggleDisabled = false,
  onExpand,
  onCollapse,
}: RecipientCardProps) {
  const nameInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    if (autoFocus && expanded && nameInputRef.current) {
      setTimeout(() => {
        nameInputRef.current?.focus();
      }, 100);
    }
  }, [autoFocus, expanded, nameInputRef.current]);

  const cardClassNames = [
    styles.recipientCard,
    expanded && styles.expanded,
    dragging && styles.dragging,
  ].filter(Boolean).join(' ');

  const headerClassNames = [
    styles.recipientHeader,
    toggleDisabled && styles.toggleDisabled,
  ].filter(Boolean).join(' ');


  function handleToggle() {
    if (!toggleDisabled) {
      if (expanded) {
        onCollapse();
      } else {
        onExpand();
      }
    }
  }

  return (
    <div
      className={cardClassNames}
      role="listitem"
      draggable="true"
      onDragStart={onDragStart}
      onDragEnd={onDragEnd}
    >
      <div
        className={headerClassNames}
        role="button"
        tabIndex={toggleDisabled ? -1 : 0}
        onClick={handleToggle}
      >
        <DragHandle />
        <RecipientSummary
          recipient={recipient}
          expanded={expanded}
          nameInputRef={nameInputRef}
          translations={t}
        />
        <RecipientActions
          recipient={recipient}
          expanded={expanded}
          translations={t}
        />
      </div>

      {expanded && (
        <RecipientDetails
          recipient={recipient}
          contactTypeOptions={contactTypeOptions}
          translations={t}
        />
      )}
    </div>
  );
}

export default RecipientCard;

// src/components/ui/RecipientCard.svelte
<script lang="ts">
  import type { Recipient, ContactInfo } from '../../lib/types/recipient';
  import ContactRow from './ContactRow.svelte';
  import Icon from './Icons.svelte';

  interface ContactTypeOption {
    value: string;
    label: string;
  }

  interface Translations {
    newRecipient: string;
    removeRecipient: string;
    addContact: string;
    removeContact: string;
    fields: {
      name: string;
      contacts: string;
      notListedPublicly: string;
      privateInfo: string;
      numberedInfo: string;
    };
    placeholders: {
      name: string;
      contactValue: string;
    };
  }

  interface Props {
    recipient: Recipient;
    expanded: boolean;
    dragging: boolean;
    contactTypeOptions: ContactTypeOption[];
    translations: Translations;
    onToggle: () => void;
    onRemove: () => void;
    onUpdateField: (field: 'name' | 'isPrivate', value: string | boolean) => void;
    onAddContact: () => void;
    onRemoveContact: (contactId: string) => void;
    onUpdateContact: (contactId: string, field: 'type' | 'value', value: string) => void;
    onDragStart: (e: DragEvent) => void;
    onDragEnd: () => void;
    autoFocus?: boolean;
    toggleDisabled?: boolean;
  }

  let {
    recipient,
    expanded,
    dragging,
    contactTypeOptions,
    translations: t,
    onToggle,
    onRemove,
    onUpdateField,
    onAddContact,
    onRemoveContact,
    onUpdateContact,
    onDragStart,
    onDragEnd,
    autoFocus = false,
    toggleDisabled = false,
  }: Props = $props();

  let nameInput: HTMLInputElement | null = $state(null);

  $effect(() => {
    if (autoFocus && expanded && nameInput) {
      // Petit délai pour s'assurer que le DOM est rendu
      setTimeout(() => {
        nameInput?.focus();
      }, 100);
    }
  });

  function handleKeydown(e: KeyboardEvent): void {
    if (toggleDisabled) return;
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault();
      onToggle();
    }
  }
  
  function handleToggle(): void {
    if (!toggleDisabled) {
      onToggle();
    }
  }

  function handleRemoveClick(e: MouseEvent): void {
    e.stopPropagation();
    onRemove();
  }

  function handlePrivateToggle(e: MouseEvent): void {
    e.stopPropagation();
    onUpdateField('isPrivate', !(recipient.isPrivate ?? false));
  }
</script>

<div
  class="recipient-card"
  class:expanded
  class:dragging
  role="listitem"
  draggable="true"
  ondragstart={onDragStart}
  ondragend={onDragEnd}
>
  <div
    class="recipient-header"
    class:toggle-disabled={toggleDisabled}
    role="button"
    tabindex={toggleDisabled ? -1 : 0}
    onclick={handleToggle}
    onkeydown={handleKeydown}
  >
    <div
      class="drag-handle"
      role="presentation"
      onclick={(e) => e.stopPropagation()}
      onkeydown={(e) => e.stopPropagation()}
    >
      <Icon name="grip-vertical" size={18} />
    </div>
    <div class="recipient-summary">
      {#if expanded}
        <div class="name-input-wrapper">
          <input
            bind:this={nameInput}
            id="name-{recipient.id}"
            type="text"
            class="form-input recipient-name-input"
            value={recipient.name}
            oninput={(e) => onUpdateField('name', e.currentTarget.value)}
            placeholder={t.placeholders.name}
            onclick={(e) => e.stopPropagation()}
            onkeydown={(e) => e.stopPropagation()}
          />
          {#if recipient.isPrivate}
            <div class="private-info-message">
              {t.fields.privateInfo}
            </div>
          {:else if recipient.number}
            <div class="private-info-message">
              {t.fields.numberedInfo}
            </div>
          {/if}
        </div>
      {:else}
        <span class="recipient-name" class:private={recipient.isPrivate ?? false}>
          {recipient.name || t.newRecipient}
          {#if recipient.number !== undefined}
            <span class="recipient-number"> (#{recipient.number})</span>
          {/if}
        </span>
      {/if}
    </div>
    <div class="recipient-actions">
      {#if expanded}
        <button
          class="private-toggle-button"
          onclick={handlePrivateToggle}
          title={t.fields.notListedPublicly}
        >
          <Icon name={recipient.isPrivate ? 'eye-off' : 'eye'} size={18} />
        </button>
      {/if}
      {#if expanded && !recipient.number}
        <button
          class="remove-button large"
          onclick={handleRemoveClick}
          title={t.removeRecipient}
        >
          <Icon name="minus" size={16} />
        </button>
      {/if}
      <span class="expand-icon" class:rotated={expanded}>
        <Icon name="chevron-right" size={20} />
      </span>
    </div>
  </div>

  {#if expanded}
    <div class="recipient-details">
      <div class="contacts-section">
        {#each recipient.contacts as contact (contact.id)}
          <ContactRow
            {contact}
            {contactTypeOptions}
            placeholders={{ value: t.placeholders.contactValue }}
            removeTitle={t.removeContact}
            onTypeChange={(type) => onUpdateContact(contact.id, 'type', type)}
            onValueChange={(value) => onUpdateContact(contact.id, 'value', value)}
            onRemove={() => onRemoveContact(contact.id)}
          />
        {/each}

        <button class="add-button" onclick={onAddContact}>
          <Icon name="plus" size={16} />
          {t.addContact}
        </button>
      </div>
    </div>
  {/if}
</div>
